name: End to End Tests - release-12.0

on:
  push:
    branches:
      - release-12.0
  pull_request:
    branches:
      - release-12.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Create Kind Cluster
      uses: helm/kind-action@v1.4.0
      with:
        cluster_name: kubernetes-python-e2e-release-12.0-${{ matrix.python-version }}
        # The kind version to be used to spin the cluster up
        # this needs to be updated whenever a new Kind version is released
        version: v0.11.1
        # Update the config here whenever a new client snapshot is performed
        # This would eventually point to cluster with the latest Kubernetes version
        # as we sync with Kubernetes upstream
        config: .github/workflows/kind-configs/cluster-1.16.yaml
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r test-requirements.txt
    - name: Install package
      run: python -m pip install -e .
    - name: Run End to End tests
      run: pytest -vvv -s kubernetes/e2e_test
